### PR TITLE
Remove CMake warnings

### PR DESCRIPTION
**Pull request by hjmallon**

### CODE REVIEW

**Comment by zbeekman** [comment]
Proposed fix for #194

**Comment by hjmallon** [comment]
@zbeekman Not sure I understand you comment. Maybe you posted it to the wrong Issue?

**Comment by zbeekman** [comment]
Yup, my mistake

**Comment by zbeekman** [comment]
@hjmallon did you submit a PR of #194 already?

**Comment by hjmallon** [comment]
I have not. The change is here in my master branch (https://github.com/hjmallon/wdt/commit/ec6bbad26527c34f52edae4adcbb5ada0c2b8ad3), but it did not cherry-pick nicely back to master so I was going to wait for other commits to be merged.

**Comment by hjmallon** [comment]
I now have (https://github.com/facebook/wdt/pull/197)

**Pull request closed without merging**
